version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  team4-database:
    container_name: team4-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: dgjinsu/team4-database
    environment:
      - MARIADB_DATABASE=food-recommendation
      - MARIADB_ROOT_PASSWORD=1234
    networks:
      - test_network_02
#    volumes:
#      - ./database/config:/etc/mysql/conf.d
#      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  team4-app:
    container_name: team4-app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://team4-database:13306/food-recommendation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - test_network_02
    depends_on:
      - team4-database
    image: dgjinsu/team4-app
    ports:
      - "80:8080"
    restart: always # depends on은 실행 순서만 컨트롤 할뿐,
    # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB 또는 Redis가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정

networks:
  test_network_02: