spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://busan-hackathon.coz9al7ljo0h.ap-northeast-2.rds.amazonaws.com:3306/recommendation
    username: root
    password: 12341234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



